### ISSUE TITLE
Draft build + deploy configuration for existing front-end

### ISSUE THREAD

**Issue by hangler** [bcgov/NewJobSurveyAdmin#2]
* [x] Separate front-end from API build in existing project
* [x] Build configuration for front-end (most likely using an s2i approach into a Caddy / nginx web server)
* [x] Deploy configuration (including extraction of parameters / secrets)

**Comment by hangler** [comment]
Have a successful proof-of-concept build of the front-end using nginx working. (Avoiding Caddy for the moment because there is no out-of-the-box image stream provided.)
